Extension detection
SamueLagunju/Crypto pull request #11
Opened 2021-02-19 05:51 UTC by SamueLagunju

2021-02-24 17:15 UTC, KaiPrince requested changes

2021-02-24 17:15 UTC, KaiPrince commented on crypto/__main__.py
> +            if any(file in filename for file in decryption_extension):
```suggestion
            if any(ext in filename for ext in decryption_extension):
```

for clarity.

2021-02-24 17:15 UTC, KaiPrince commented on crypto/__main__.py
> +            if any(file in filename for file in encryption_extension):
```suggestion
            elif any(file in filename for file in encryption_extension):
```
these two cases should be mutually exclusive.

2021-02-24 17:15 UTC, KaiPrince commented on crypto/__main__.py
> +            if any(file in filename for file in encryption_extension):
```suggestion
            if any(ext in filename for ext in encryption_extension):
```

2021-02-24 17:15 UTC, KaiPrince commented on crypto/__main__.py
> +            new_file = convert_ext(filename)
The output is written to `filename`, but then the a new file name is made by `convert_ext`, which is then never used.
Is `write_file` writing to the wrong file?

2021-03-03 01:36 UTC, SamueLagunju reviewed
This looks good to me.

2021-03-03 01:37 UTC, merged