Convert Extension Refactor
SamueLagunju/Crypto pull request #12
Opened 2021-03-03 05:13 UTC by SamueLagunju

2021-03-04 16:51 UTC, KaiPrince commented
In summary, it seems like we've opened a can of worms. It may be time to re-think and ask "what is the Crypter class? Why does it exist, and what's its responsibility? Is it a do-er or a coordinator?". This is totally normal when refactoring; it often requires you to critically re-examine the structures you had previously decided on. Good work on extending the strategy class.

2021-03-04 16:52 UTC, KaiPrince requested changes
In summary, it seems like we've opened a can of worms. It may be time to re-think and ask "what is the Crypter class? Why does it exist, and what's its responsibility? Is it a do-er or a coordinator?". This is totally normal when refactoring; it often requires you to critically re-examine the structures you had previously decided on. Good work on extending the strategy class.

2021-03-04 16:52 UTC, KaiPrince commented on crypto/__main__.py
>              crypter = Crypter(filename, SeanStrategy())
The Crypter class never uses this filename. In fact, right now it's basically an empty class. I think it should either be given more responsibilities, or removed.

2021-03-04 16:52 UTC, KaiPrince commented on crypto/__main__.py
> +            new_file_name = crypter.convert_ext(filename, file_extension)
Be careful, there are two places in the other if clauses where you forgot to repoint this function.

I think it's indicative of a larger issue: you have too much code duplication. Consider that this elif clause is just a combination of the two above it, but there is no code reuse between them.

Two possible remedies are to extract the common logic to new functions, or to push the logic down into the Crypter class.

2021-03-04 16:52 UTC, KaiPrince commented on crypto/crypter.py
> +    def convert_ext(self, file_name, old_ext):
If you end up moving logic into this class, you may find this method unnecessary. Or, at least, worth making private.

2021-03-04 16:52 UTC, KaiPrince commented on crypto/__main__.py
>                  output_text = crypter.decrypt_txt(file_contents)
You may find that you need to rename the decrypt_txt family of functions in both Crypter and Strategy to reflect the new possibility of non-ascii (binary) file data.

2021-03-06 06:19 UTC, SamueLagunju reviewed
Will be applying main logic to crypter class

2021-03-06 14:24 UTC, KaiPrince commented on crypto/__main__.py
> +                        list_of_files.append(file)
```suggestion
    for element in rules:
        for file in element:
            if validate_file(file):
                list_of_files.append(file)
```

c'mon man...

2021-03-06 14:44 UTC, SamueLagunju commented on crypto/__main__.py
> +                        list_of_files.append(file)
late night programming 🤦🏾‍♂️

2021-03-23 20:14 UTC, SamueLagunju reviewed
GOAT Pull request merge into mediocre PR

2021-03-27 05:09 UTC, SamueLagunju reviewed
Changes have been implemented. I think we've refactored enough of the project

2021-03-28 03:52 UTC, merged

2021-04-26 16:48 UTC, SamueLagunju reviewed
Tidying Up.